alliance_auth/urls.py
from django.conf.urls import patterns, include, url

from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _
from django.contrib import admin

admin.autodiscover()

# Functional/Untranslated URL's
urlpatterns = patterns('',
                       
                       # Locale
                       url(r'^i18n/', include('django.conf.urls.i18n')),

                       # Admin urls
                       url(r'^admin/', include(admin.site.urls)),

                       # Index
                       url(_(r'^$'), 'portal.views.index_view', name='auth_index'),
                       
                       # Authentication
                       url(r'^logout_user/', 'authentication.views.logout_user', name='auth_logout_user'),

                       # Eve Online
                       url(r'^main_character_change/(\w+)/$', 'eveonline.views.main_character_change',
                           name='auth_main_character_change'),

                       # Forum Service Control
                       url(r'^activate_forum/$', 'services.views.activate_forum', name='auth_activate_forum'),
                       url(r'^deactivate_forum/$', 'services.views.deactivate_forum', name='auth_deactivate_forum'),
                       url(r'^reset_forum_password/$', 'services.views.reset_forum_password',
                           name='auth_reset_forum_password'),
                       url(r'^set_forum_password/$', 'services.views.set_forum_password', name='auth_set_forum_password'),

                       # Jabber Service Control
                       url(r'^activate_jabber/$', 'services.views.activate_jabber', name='auth_activate_jabber'),
                       url(r'^deactivate_jabber/$', 'services.views.deactivate_jabber', name='auth_deactivate_jabber'),
                       url(r'^reset_jabber_password/$', 'services.views.reset_jabber_password',
                           name='auth_reset_jabber_password'),

                       # Mumble service control
                       url(r'^activate_mumble/$', 'services.views.activate_mumble', name='auth_activate_mumble'),
                       url(r'^deactivate_mumble/$', 'services.views.deactivate_mumble', name='auth_deactivate_mumble'),
                       url(r'^reset_mumble_password/$', 'services.views.reset_mumble_password',
                           name='auth_reset_mumble_password'),
                       url(r'^set_mumble_password/$', 'services.views.set_mumble_password', name='auth_set_mumble_password'),

                       # Ipboard service control
                       url(r'^activate_ipboard/$', 'services.views.activate_ipboard_forum',
                           name='auth_activate_ipboard'),
                       url(r'^deactivate_ipboard/$', 'services.views.deactivate_ipboard_forum',
                           name='auth_deactivate_ipboard'),
                       url(r'^reset_ipboard_password/$', 'services.views.reset_ipboard_password',
                           name='auth_reset_ipboard_password'),
                       url(r'^set_ipboard_password/$', 'services.views.set_ipboard_password', name='auth_set_ipboard_password'),

                       # XenForo service control
                       url(r'^activate_xenforo/$', 'services.views.activate_xenforo_forum',
                           name='auth_activate_xenforo'),
                       url(r'^deactivate_xenforo/$', 'services.views.deactivate_xenforo_forum',
                           name='auth_deactivate_xenforo'),
                       url(r'^reset_xenforo_password/$', 'services.views.reset_xenforo_password',
                           name='auth_reset_xenforo_password'),
                       url(r'^set_xenforo_password/$', 'services.views.set_xenforo_password', name='auth_set_xenforo_password'), 

                       # Teamspeak3 service control
                       url(r'^activate_teamspeak3/$', 'services.views.activate_teamspeak3',
                           name='auth_activate_teamspeak3'),
                       url(r'^deactivate_teamspeak3/$', 'services.views.deactivate_teamspeak3',
                           name='auth_deactivate_teamspeak3'),
                       url(r'reset_teamspeak3_perm/$', 'services.views.reset_teamspeak3_perm',
                           name='auth_reset_teamspeak3_perm'),

                       # Discord Service Control
                       url(r'^activate_discord/$', 'services.views.activate_discord', name='auth_activate_discord'),
                       url(r'^deactivate_discord/$', 'services.views.deactivate_discord', name='auth_deactivate_discord'),
                       url(r'^reset_discord/$', 'services.views.reset_discord', name='auth_reset_discord'),
                       url(r'^discord_callback/$', 'services.views.discord_callback', name='auth_discord_callback'),
                       url(r'^discord_add_bot/$', 'services.views.discord_add_bot', name='auth_discord_add_bot'),
                       
                       # Discourse Service Control
                       url(r'^activate_discourse/$', 'services.views.activate_discourse', name='auth_activate_discourse'),
                       url(r'^deactivate_discourse/$', 'services.views.deactivate_discourse', name='auth_deactivate_discourse'),

                       # IPS4 Service Control
                       url(r'^activate_ips4/$', 'services.views.activate_ips4',
                           name='auth_activate_ips4'),
                       url(r'^deactivate_ips4/$', 'services.views.deactivate_ips4',
                           name='auth_deactivate_ips4'),
                       url(r'^reset_ips4_password/$', 'services.views.reset_ips4_password',
                           name='auth_reset_ips4_password'),
                       url(r'^set_ips4_password/$', 'services.views.set_ips4_password', name='auth_set_ips4_password'),

                       # SMF Service Control
                       url(r'^activate_smf/$', 'services.views.activate_smf', name='auth_activate_smf'),
                       url(r'^deactivate_smf/$', 'services.views.deactivate_smf', name='auth_deactivate_smf'),
                       url(r'^reset_smf_password/$', 'services.views.reset_smf_password',
                           name='auth_reset_smf_password'),
                       url(r'^set_smf_password/$', 'services.views.set_smf_password', name='auth_set_smf_password'),

                       # Alliance Market Control
                       url(r'^activate_market/$', 'services.views.activate_market', name='auth_activate_market'),
                       url(r'^deactivate_market/$', 'services.views.deactivate_market', name='auth_deactivate_market'),
                       url(r'^reset_market_password/$', 'services.views.reset_market_password',
                           name='auth_reset_market_password'),
                       url(r'^set_market_password/$', 'services.views.set_market_password', name='auth_set_market_password'),

                       # Pathfinder Control
                       url(r'^activate_pathfinder/$', 'services.views.activate_pathfinder', name='auth_activate_pathfinder'),
                       url(r'^deactivate_pathfinder/$', 'services.views.deactivate_pathfinder', name='auth_deactivate_pathfinder'),
                       url(r'^reset_pathfinder_password/$', 'services.views.reset_pathfinder_password',
                           name='auth_reset_pathfinder_password'),
                       url(r'^set_pathfinder_password/$', 'services.views.set_pathfinder_password', name='auth_set_pathfinder_password'),

                       # SRP URLS
                       url(r'^srp_fleet_remove/(\w+)$', 'srp.views.srp_fleet_remove', name='auth_srp_fleet_remove'),
                       url(r'^srp_fleet_disable/(\w+)$', 'srp.views.srp_fleet_disable', name='auth_srp_fleet_disable'),
                       url(r'^srp_fleet_enable/(\w+)$', 'srp.views.srp_fleet_enable', name='auth_srp_fleet_enable'),
                       url(r'^srp_fleet_mark_completed/(\w+)', 'srp.views.srp_fleet_mark_completed',
                           name='auth_srp_fleet_mark_completed'),
                       url(r'^srp_fleet_mark_uncompleted/(\w+)', 'srp.views.srp_fleet_mark_uncompleted',
                           name='auth_srp_fleet_mark_uncompleted'),
                       url(r'^srp_request_remove/(\w+)', 'srp.views.srp_request_remove',
                           name="auth_srp_request_remove"),
                       url(r'srp_request_approve/(\w+)', 'srp.views.srp_request_approve',
                           name='auth_srp_request_approve'),
                       url(r'srp_request_reject/(\w+)', 'srp.views.srp_request_reject', name='auth_srp_request_reject'),

                       # Notifications
                       url(r'^remove_notifications/(\w+)/$', 'notifications.views.remove_notification', name='auth_remove_notification'),
)

# User viewed/translated URLS
urlpatterns += i18n_patterns('',

                       #corputils
                       url(r'^corputils/$', 'corputils.views.corp_member_view', name='auth_corputils'),
                       url(r'^corputils/(?P<corpid>[0-9]+)/$', 'corputils.views.corp_member_view'),
                       url(r'^corputils/(?P<corpid>[0-9]+)/(?P<year>[0-9]+)/(?P<month>[0-9]+)/$', 'corputils.views.corp_member_view', name='auth_corputils_month'),
                       url(r'^corputils/search/$', 'corputils.views.corputils_search', name="auth_corputils_search"),
                       url(r'^corputils/search/(?P<corpid>[0-9]+)/$', 'corputils.views.corputils_search'),

                       # FLEET FITTINGS
                       url(r'^fits/$', 'services.views.fleet_fits', name='auth_fleet_fits'),
                       
                       #Fleetup
                       url(r'^fleetup/$', 'fleetup.views.fleetup_view', name='auth_fleetup_view'),

srp/models.py
from django.db import models
from django.utils import timezone
from eveonline.models import EveCharacter


class SrpFleetMain(models.Model):
    fleet_name = models.CharField(max_length=254, default="")
    fleet_doctrine = models.CharField(max_length=254, default="")
    fleet_time = models.DateTimeField()
    fleet_srp_code = models.CharField(max_length=254, default="")
    fleet_srp_status = models.CharField(max_length=254, default="")
    fleet_commander = models.ForeignKey(EveCharacter)
    fleet_srp_aar_link = models.CharField(max_length=254, default="")

    def __str__(self):
        return self.fleet_name + " - SrpFleetMain"


class SrpUserRequest(models.Model):
    killboard_link = models.CharField(max_length=254, default="")
    after_action_report_link = models.CharField(max_length=254, default="")
    additional_info = models.CharField(max_length=254, default="")
    srp_status = models.CharField(max_length=254, default="")
    srp_total_amount = models.BigIntegerField(default=0)
    character = models.ForeignKey(EveCharacter)
    srp_fleet_main = models.ForeignKey(SrpFleetMain)
    kb_total_loss = models.BigIntegerField(default=0)
    srp_ship_name = models.CharField(max_length=254, default="") 
    post_time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.character.character_name + " - SrpUserRequest"

hrapplications/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

class HRApplicationCommentForm(forms.Form):
    comment = forms.CharField(widget=forms.Textarea, required=False, label=_("Comment"))

class HRApplicationSearchForm(forms.Form):
    search_string = forms.CharField(max_length=254, required=True, label=_("Search String"))

fleetup/views.py
import datetime
from operator import itemgetter, attrgetter, methodcaller

from django.utils.timezone import utc

from django.conf import settings
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import HttpResponseRedirect
from django.template.defaulttags import register
from django.contrib.humanize.templatetags.humanize import intword

from collections import namedtuple

from authentication.managers import AuthServicesInfoManager
from util import check_if_user_has_permission
from services.managers.eve_api_manager import EveApiManager
from services.managers.fleetup_manager import FleetUpManager
from eveonline.models import EveCorporationInfo
from eveonline.models import EveAllianceInfo
from eveonline.models import EveCharacter
from authentication.models import AuthServicesInfo

import logging

logger = logging.getLogger(__name__)

@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)

def fleetup_util_test(user):
    return check_if_user_has_permission(user, 'member') or check_if_user_has_permission(user, 'blue_member')

@login_required
@user_passes_test(fleetup_util_test)
def fleetup_view(request):
    logger.debug("fleetup_view called by user %s" % request.user)

    operations_list = FleetUpManager.get_fleetup_operations()
    timers_list = FleetUpManager.get_fleetup_timers()
    now = datetime.datetime.now().strftime('%H:%M:%S')

    context = {"timers_list": sorted(timers_list.items()),
               "operations_list": sorted(operations_list.items()),
               "now": now}

    return render_to_response('registered/fleetup.html',context, context_instance=RequestContext(request) )

@login_required
@permission_required('auth.human_resources')
def fleetup_characters(request):
    logger.debug("fleetup_characters called by user %s" % request.user)

    member_list = FleetUpManager.get_fleetup_members()

    context = {"member_list": sorted(member_list.items())}

    return render_to_response('registered/fleetupcharacters.html',context, context_instance=RequestContext(request) )

@login_required
@user_passes_test(fleetup_util_test)
def fleetup_fittings(request):
    logger.debug("fleetup_fittings called by user %s" % request.user)
    fitting_list = FleetUpManager.get_fleetup_fittings()
    context = {"fitting_list": sorted(fitting_list.items())}
    return render_to_response('registered/fleetupfittingsview.html',context, context_instance=RequestContext(request) )

@login_required
@user_passes_test(fleetup_util_test)
def fleetup_fitting(request, fittingnumber):
    logger.debug("fleetup_fitting called by user %s" % request.user)
    fitting_eft = FleetUpManager.get_fleetup_fitting_eft(fittingnumber)
    fitting_data = FleetUpManager.get_fleetup_fitting(fittingnumber)
    doctrinenumber = FleetUpManager.get_fleetup_doctrineid(fittingnumber)
    doctrines_list = FleetUpManager.get_fleetup_doctrine(doctrinenumber)
    context = {"fitting_eft": fitting_eft,
               "fitting_data": fitting_data,
               "doctrines_list": doctrines_list}
    return render_to_response('registered/fleetupfitting.html',context, context_instance=RequestContext(request) )


@login_required
@user_passes_test(fleetup_util_test)
def fleetup_doctrines(request):
    logger.debug("fleetup_doctrines called by user %s" % request.user)
    doctrines_list = FleetUpManager.get_fleetup_doctrines()
    context = {"doctrines_list": doctrines_list}
    return render_to_response('registered/fleetupdoctrinesview.html',context, context_instance=RequestContext(request) )

@login_required
@user_passes_test(fleetup_util_test)
def fleetup_doctrine(request, doctrinenumber):
    logger.debug("fleetup_doctrine called by user %s" % request.user)
    doctrine = FleetUpManager.get_fleetup_doctrine(doctrinenumber)
    context = {"doctrine": doctrine}
    return render_to_response('registered/fleetupdoctrine.html',context, context_instance=RequestContext(request) )

notifications/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Notification
from django.contrib.auth.decorators import login_required
import logging

logger = logging.getLogger(__name__)

@login_required
def notification_list(request):
    logger.debug("notification_list called by user %s" % request.user)
    new_notifs = Notification.objects.filter(user=request.user).filter(viewed=False)
    old_notifs = Notification.objects.filter(user=request.user).filter(viewed=True)
    logger.debug("User %s has %s unread and %s read notifications" % (request.user, len(new_notifs), len(old_notifs)))
    context = {
        'read': old_notifs,
        'unread': new_notifs,
    }
    return render(request, 'registered/notification_list.html', context)

@login_required
def notification_view(request, notif_id):
    logger.debug("notification_view called by user %s for notif_id %s" % (request.user, notif_id))
    notif = get_object_or_404(Notification, pk=notif_id)
    if notif.user == request.user:
        logger.debug("Providing notification for user %s" % request.user)
        context = {'notif': notif}
        notif.view()
        return render(request, 'registered/notification_view.html', context)
    else:
        logger.warn("User %s not authorized to view notif_id %s belonging to user %s" % (request.user, notif_id, notif.user))
        return redirect('auth_notification_list')

@login_required
def remove_notification(request, notif_id):
    logger.debug("remove notification called by user %s for notif_id %s" % (request.user, notif_id))
    notif = get_object_or_404(Notification, pk=notif_id)
    if notif.user == request.user:
        if Notification.objects.filter(id=notif_id).exists():
            notif.delete()
            logger.info("Deleting notif id %s by user %s" % (notif_id, request.user))
    else:
        logger.error("Unable to delete notif id %s for user %s - notif matching id not found." % (notif_id, request.user))
    return redirect('auth_notification_list')

stock/templates/registered/apikeymanagment.html
{% extends "public/base.html" %}
{% load bootstrap %}
{% load staticfiles %}
{% load i18n %}

{% block title %}Alliance Auth{% endblock %}

{% block page_title %}{% trans "API Key Management" %}{% endblock page_title %}
{% block extra_css %}{% endblock extra_css %}

{% block content %}
    <div class="col-lg-12">
        <div class="row">
            {% if apikeypairs %}
            {% else %}
                <div class="alert alert-danger" role="alert">{% trans "No api keys found" %}</div>
            {% endif %}
            <h1 class="page-header text-center">{% trans "API Key Management" %}
                <div class="text-right">
                    <a href="{% url 'auth_add_api_key' %}">
                        <button type="button" class="btn btn-success">{% trans "Add Key" %}</button>
                    </a>
                </div>
            </h1>
            <table class="table table-bordered">
                <tr>
                    <th class="text-center">{% trans "API ID" %}</th>
                    <th class="text-center">{% trans "API Key" %}</th>
                    <th class="text-center">{% trans "Action" %}</th>
                </tr>
                {% for pair in apikeypairs %}
                    <tr>
                        <td class="text-center">{{ pair.api_id }}</td>
                        <td class="text-center">{{ pair.api_key }}</td>
                        <td class="text-center">
                            <a href="/refresh_api_pair/{{ pair.api_id }}">
                                <button type="button" class="btn btn-success"><span
                                        class="glyphicon glyphicon-refresh"></span></button>
                            </a>
                            <a href="/delete_api_pair/{{ pair.api_id }}">
                                <button type="button" class="btn btn-danger"><span
                                        class="glyphicon glyphicon-remove"></span></button>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>

{% endblock content %}

stock/templates/registered/fatlinkpersonalstatisticsview.html
{% extends "public/base.html" %}
{% load bootstrap %}
{% load staticfiles %}
{% load i18n %}

{% block title %}Alliance Auth{% endblock %}
{% block page_title %}{% trans "Personal fatlink statistics" %}{% endblock page_title %}

{% block content %}
    <div class="col-lg-12">
        <h1 class="page-header text-center">{% trans "Participation data statistics for" %} {{ year }}
            <div class="text-right">
                <a href="{% url 'auth_fatlink_view_personal_statistics_year' previous_year %}">
                    <button type="button" class="btn btn-info">{% trans "Previous year" %}</button>
                </a>
                {%  if next_year %}
                <a href="{% url 'auth_fatlink_view_personal_statistics_year' next_year  %}">
                    <button type="button" class="btn btn-info">{% trans "Next year" %}</button>
                </a>
                {%  endif %}
            </div>
        </h1>
        <table class="table table-responsive table-bordered">
            <tr>
                <th class="col-md-2 text-center">{% trans "Month" %}</th>
                <th class="col-md-2 text-center">{% trans "Fats" %}</th>
            </tr>
            {% for monthnr, month, n_fats in monthlystats %}
            <tr>
                <td class="text-center">
                    <a href="{% url 'auth_fatlink_view_personal_statistics_month' year monthnr %}">
                        {{ month }}
                    </a>
                </td>
                <td class="text-center">{{ n_fats }}</td>
            </tr>
            {% endfor %}
        </table>
    </div>


<script src="/static/js/dateformat.js"></script>

{% endblock content %}

stock/templates/registered/fatlinkstatisticsview.html
{% extends "public/base.html" %}
{% load bootstrap %}
{% load staticfiles %}
{% load i18n %}

{% block title %}Alliance Auth{% endblock %}
{% block page_title %}{% trans "Fatlink statistics" %}{% endblock page_title %}

{% block content %}
    <div class="col-lg-12">
        <h1 class="page-header text-center">{% blocktrans %}Participation data statistics for {{ month }}, {{ year }}{% endblocktrans %}
            <div class="text-right">
                <a href="{% url 'auth_fatlink_view_statistics_month' previous_month|date:"Y" previous_month|date:"m"  %}">
                    <button type="button" class="btn btn-info">{% trans "Previous month" %}</button>
                </a>
                {%  if next_month %}
                <a href="{% url 'auth_fatlink_view_statistics_month' next_month|date:"Y" next_month|date:"m"  %}">
                    <button type="button" class="btn btn-info">{% trans "Next month" %}</button>
                </a>
                {%  endif %}
            </div>
        </h1>
        <table class="table table-responsive table-bordered">
            <tr>
                <th class="col-md-1"></th>
                <th class="col-md-2 text-center">{% trans "Ticker" %}</th>
                <th class="col-md-5 text-center">{% trans "Corp" %}</th>
                <th class="col-md-2 text-center">{% trans "Members" %}</th>
                <th class="col-md-2 text-center">{% trans "Fats" %}</th>
                <th class="col-md-2 text-center">{% trans "Average fats" %}</th>
            </tr>
            {% for corpStat in fatStats %}
            <tr>
                <td>
                    <img src="https://image.eveonline.com/Corporation/{{ corpStat.corp.corporation_id }}_32.png" class="ra-avatar img-responsive">
                </td>
                <td class="text-center">[{{ corpStat.corp.corporation_ticker }}]</td>
                <td class="text-center">{{ corpStat.corp.corporation_name }}</td>
                <td class="text-center">{{ corpStat.corp.member_count }}</td>
                <td class="text-center">{{ corpStat.n_fats }}</td>
                <td class="text-center">{{ corpStat.avg_fat }}</td>
            </tr>
            {% endfor %}
        </table>
    </div>


<script src="/static/js/dateformat.js"></script>

{% endblock content %}

stock/templates/registered/fleetupcharacters.html
{% extends "public/base.html" %}
{% load bootstrap %}
{% load staticfiles %}
{% load i18n %}

{% block title %}Alliance Auth{% endblock %}
{% block page_title %}FleetUp{% endblock page_title %}

{% block content %}
<div class="col-lg-12">
{% if perms.auth.corp_stats %}
    <nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">{% trans "Toggle navigation" %}</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Fleet-Up</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/fleetup/">{% trans "Ops and Timers" %}</a></li>
                <li><a href="/fleetup/doctrines/">{% trans "Doctrines" %}</a></li>
                <li><a href="/fleetup/fittings/">{% trans "Fittings" %}</a></li>
                
                <li class="active"><a href="/fleetup/characters/">{% trans "Characters" %} <span class="sr-only">(current)</span></a></li>
                
                <li></li>
            </ul>
        </div>
    </div>
    </nav>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">{% trans "Characters registered on Fleet-Up.com" %}</h3>
        </div>
            <div class="panel-body">
                <div class="col-lg-6">
                    <div class="table-responsive">   
                    <table class="table table-condensed table-hover table-striped">
                        <tr>
                            <th class="col-md-1"></th>
                            <th class="col-md-1">{% trans "Character" %}</th>
                            <th class="col-md-1">{% trans "Corporation" %}</th>
                            <th class="col-md-1">Fleet-Up(id)</th>
                        </tr>
                        {% for char_name, user_id in member_list %}
                        <tr>
                            <td>
                                <img src="http://image.eveonline.com/Character/{{ user_id.char_id }}_32.jpg" class="img-circle">
                            </td>
                            <td>
                                <p>{{ user_id.char_name }}</p>
                            </td>
                            <td>
                                <p>{{ user_id.corporation }}</p>
                            </td>
                            <td>
                                <p>{{ user_id.user_id }}</p>
                            </td>
                        {% endfor %}
                    </table>
                    </div>
                </div>
            </div>
    </div>
{% endif %}
</div>
{% endblock content %}

stock/templates/registered/hrapplicationcreate.html
{% extends "public/base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block title %}Apply To {{ corp.corporation_name }}{% endblock title %}
{% block page_title %}{% trans "Apply To" %} {{ corp.corporation_name }}{% endblock page_title %}
{% block content %}
    <div class="col-lg-12">
        <h1 class="page-header text-center">{% trans "Apply To" %} {{ corp.corporation_name }}</h1>
        <div class="container-fluid">
            <div class="col-md-4 col-md-offset-4">
                <div class="row">
                    <form class="form-signin">
                        {% csrf_token %}
                        {% for question in questions %}
                            <div class="form-group">
                                <label class="control-label" for="id_{{ question.pk }}">{{ question.title }}</label>
                                <div class=" ">
                                    {% if question.help_text %}
                                        <div cass="text-center">{{ question.help_text }}</div>
                                    {% endif %}
                                    <textarea class="form-control" cols="40" id="id_{{ question.pk }}" name="{{ question.pk }}" rows="10"></textarea>
                                </div>
                            </div>
                        {% endfor %}
                        <button class="btn btn-lg btn-primary btn-block" type="submit" formmethod="post">{% trans "Submit" %}</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
                        

stock/templates/registered/hrcreateapplication.html
{% extends "public/base.html" %}
{% load bootstrap %}
{% load staticfiles %}
{% load i18n %}

{% block title %}Alliance Auth - Create Application{% endblock %}

{% block page_title %}{% trans "Create Application" %}{% endblock page_title %}
{% block extra_css %}{% endblock extra_css %}

{% block content %}
    <div class="col-lg-12">
        <h1 class="page-header text-center">{% trans "Create Application" %}</h1>

        <div class="container-fluid">
            <div class="col-md-4 col-md-offset-4">
                <div class="row">
                    {% if success %}
                        <div class="alert alert-success text-center" role="alert">{% trans "Application Submitted" %}</div>
                    {% else %}
                        <form class="form-signin" role="form" action="" method="POST">
                            {% csrf_token %}
                            {{ form|bootstrap }}
                            <br/>
                            <button class="btn btn-lg btn-primary btn-block" type="submit">{% trans "Submit Application" %}</button>
                        </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

stock/templates/registered/srpfleetrequestamount.html
{% extends "public/base.html" %}
{% load bootstrap %}
{% load staticfiles %}
{% load i18n %}

{% block title %}Alliance Auth - Update SRP Amount{% endblock %}

{% block page_title %}{% trans "Update SRP Amount" %}{% endblock page_title %}
{% block extra_css %}
    <link href="{% static 'css/jquery.datetimepicker.css' %}" rel="stylesheet" type="text/css">{% endblock extra_css %}

{% block content %}

    <div class="col-lg-12">
        <h1 class="page-header text-center">{% trans "Update SRP Amount" %}</h1>

        <div class="container-fluid">
            <div class="col-md-4 col-md-offset-4">
                <div class="row">
                    {% if no_srp_code %}
                        <div class="alert alert-danger" role="alert">{% trans "SRP Code Does Not Exist" %}</div>
                    {% else %}
                        <form class="form-signin" role="form" action="" method="POST">
                            {% csrf_token %}
                            {{ form|bootstrap }}
                            <br/>
                            <button class="btn btn-lg btn-primary btn-block" type="submit">{% trans "Update SRP Request Amount" %}
                            </button>
                        </form>
                    {% endif %}
                </div>
            </div>
        </div>

    </div>

{% endblock content %}

{% block extra_script %}

    $('#id_fleet_time').datetimepicker({
    maskInput: true,
    format: 'Y-m-d H:i',minDate:0
    });

{% endblock extra_script %}